### ISSUE TITLE
对这个项目很感兴趣！

### ISSUE THREAD

**Issue by kkkgo** [KiritoA/c3h_client#1]
偶然看到这个认证程序支持7.0 代码很简洁 编译起来没什么障碍 我楼上的小伙伴成功运行跑起来了~
不过奇怪的是我这里跑不起来=。=~~
测试了几个客户端，发现YaH3c（https://github.com/humiaozuzu/YaH3C）可以成功验证，其他的不可以。但是python跑起来不太稳定 移植到路由上额比较占空间和内存╮(╯▽╰)╭ 而且YaH3C在楼上跑不起来，提示的是密码错误：
==> Sending EAP response with password
==> Got EAP Failure
## 本人才疏学浅，顺藤摸瓜找到这段代码：

elif reqtype == EAP_TYPE_H3C:
                display_prompt(Fore.YELLOW, 'Got EAP Request for Allocation')
                self.send_response_h3c(id)
                display_prompt(Fore.GREEN, 'Sending EAP response with password')
 elif reqtype == EAP_TYPE_MD5:
                data_len = unpack("!B", reqdata[0:1])[0]
                md5data = reqdata[1:1 + data_len]
                display_prompt(Fore.YELLOW, 'Got EAP Request for MD5-Challenge')
                self.send_response_md5(id, md5data)
##                 display_prompt(Fore.GREEN, 'Sending EAP response with password')

我的猜想是这样的，楼上收到的是MD5的请求，我这里收到的是H3C的请求，（我不懂请允许我这么叫法），YaH3C处理H3C的请求对我这里能用，而处理MD5的请求就不行，会导致认为密码发送错误，而c3h_client处理MD5的请求就好用，但无法识别（我猜？）H3C类型的请求，没办法处理？

瞎扯了这么多，还是想作者帮忙看看，怎么把YaH3C的处理H3C类型的请求加进去？这样我就可以编译openwrt的版本扔进路由跑了，路由跑python还是压力比较大。无论如何，还是感谢作者分享这个源码。（’・ω・‘）

**Comment by KiritoA** [comment]
抱歉啊我没怎没研究过YaH3C的代码，因为我不太会python。。你可以尝试抓包分析一下，根据你校园网的环境修改代码

**Comment by kkkgo** [comment]
我抓了几个包，inode官方客户端、YaH3C、c3h_client，本人才疏学浅，希望有空帮忙看看，感激不尽~！
http://03k.org/go/inode-pcapng
