### ISSUE TITLE
make src下的文件失败

### ISSUE THREAD

**Issue by zfireear** [KiritoA/c3h_client#5]
错误信息如下：
> gcc -c -DNDEBUG -Wall -g -O2 auth.c
> auth.c:18:18: fatal error: pcap.h: No such file or directory
> compilation terminated.
> Makefile:22: recipe for target 'auth.o' failed
> make: *** [auth.o] Error 1

**Comment by YianAndCode** [comment]
请确保已经安装 `libpcap`（`libpcap-dev`） 依赖
