### ISSUE TITLE
c3h-refresh: not found

### ISSUE THREAD

**Issue by DavidZhang73** [KiritoA/c3h_client#6]
http://www.right.com.cn/forum/forum.php?mod=viewthread&tid=217637&highlight=h3c编译的文件，因为路由器tomato没有opkg，所以直接解压缩放进的路由器
C3H Client 15.12
C3H Client: Connecting to the network ....
C3H Client: Server responded
C3H Client: Beginning authentication... [************]
C3H Client: Authenticating password...
C3H Client: You have passed the identity authentication
C3H Client: Obtaining IP address...
sh: ./c3h-refresh: not found
最后那个文件找不到啊，希望能够得到帮助

**Comment by KiritoA** [comment]
请先参考 njit8021xclient 的 [RefreshIP.py](https://github.com/liuqun/njit8021xclient/blob/master/src/RefreshIP.py)，本项目的文件稍后测试再补上
